export const categories = {
  ofertones: {
    name: 'Ofertones',
    description: 'Descubre nuestras mejores ofertas con descuentos de hasta 50%',
    icon: '🔥',
  },
  'guia-regalos': {
    name: 'Guía de Regalos',
    description: 'Encuentra el regalo perfecto para tus seres queridos',
    icon: '🎁',
  },
  moviles: {
    name: 'Móviles',
    description: 'Los últimos modelos de smartphones reacondicionados',
    icon: '📱',
  },
  portatiles: {
    name: 'Portátiles',
    description: 'Laptops y computadoras portátiles de marcas reconocidas',
    icon: '💻',
  },
  tablets: {
    name: 'Tablets',
    description: 'Tablets reacondicionadas para trabajo y entretenimiento',
    icon: '📲',
  },
  consolas: {
    name: 'Consolas',
    description: 'Consolas de videojuegos reacondicionadas',
    icon: '🎮',
  },
  smartwatches: {
    name: 'Smartwatches',
    description: 'Relojes inteligentes y wearables',
    icon: '⌚',
  },
  audio: {
    name: 'Audio',
    description: 'Auriculares, altavoces y equipos de audio premium',
    icon: '🎧',
  },
  electrodomesticos: {
    name: 'Electrodomésticos',
    description: 'Electrodomésticos reacondicionados para tu hogar',
    icon: '🏠',
  },
  mas: {
    name: 'Más Categorías',
    description: 'Explora nuestro amplio catálogo de productos',
    icon: '➕',
  },
};

export const categoryProducts: Record<string, any[]> = {
  ofertones: [
    {
      id: 'oferta-1',
      name: 'iPhone 13 Pro',
      price: 69900,
      originalPrice: 99900,
      image: 'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Súper Oferta',
      condition: 'Aspecto excelente',
      rating: 4.8,
      reviews: 245,
      discount: 30,
    },
    {
      id: 'oferta-2',
      name: 'Dron DJI Air 2S',
      price: 79900,
      originalPrice: 119900,
      image: 'https://images.pexels.com/photos/1526170/pexels-photo-1526170.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Súper Oferta',
      condition: 'Aspecto excelente',
      rating: 4.8,
      reviews: 145,
      discount: 33,
    },
    {
      id: 'oferta-3',
      name: 'Samsung Galaxy S21',
      price: 59900,
      originalPrice: 89900,
      image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Súper Oferta',
      condition: 'Buen estado',
      rating: 4.5,
      reviews: 189,
      discount: 33,
    },
    {
      id: 'oferta-4',
      name: 'iPad Air',
      price: 39900,
      originalPrice: 59900,
      image: 'https://images.pexels.com/photos/546822/pexels-photo-546822.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Súper Oferta',
      condition: 'Buen estado',
      rating: 4.6,
      reviews: 128,
      discount: 33,
    },
    {
      id: 'oferta-5',
      name: 'Dell XPS 13',
      price: 89900,
      originalPrice: 129900,
      image: 'https://images.pexels.com/photos/18105/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Súper Oferta',
      condition: 'Buen estado',
      rating: 4.7,
      reviews: 234,
      discount: 31,
    },
    {
      id: 'oferta-6',
      name: 'PlayStation 5',
      price: 49900,
      originalPrice: 69900,
      image: 'https://images.pexels.com/photos/1334601/pexels-photo-1334601.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Súper Oferta',
      condition: 'Como nuevo',
      rating: 4.9,
      reviews: 567,
      discount: 29,
    },
    {
      id: 'oferta-7',
      name: 'Cámara Canon EOS',
      price: 64900,
      originalPrice: 99900,
      image: 'https://images.pexels.com/photos/606941/pexels-photo-606941.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Súper Oferta',
      condition: 'Muy bueno',
      rating: 4.8,
      reviews: 103,
      discount: 35,
    },
    {
      id: 'oferta-8',
      name: 'Sony WH-1000XM5',
      price: 34900,
      originalPrice: 47900,
      image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Aspecto excelente',
      rating: 4.8,
      reviews: 298,
      discount: 27,
    },
    {
      id: 'oferta-9',
      name: 'Lavadora LG',
      price: 74900,
      originalPrice: 109900,
      image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Súper Oferta',
      condition: 'Aspecto excelente',
      rating: 4.7,
      reviews: 234,
      discount: 32,
    },
    {
      id: 'oferta-10',
      name: 'iPad Pro 12.9"',
      price: 74900,
      originalPrice: 109900,
      image: 'https://images.pexels.com/photos/546822/pexels-photo-546822.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Súper Oferta',
      condition: 'Aspecto excelente',
      rating: 4.8,
      reviews: 312,
      discount: 32,
    },
    {
      id: 'oferta-11',
      name: 'MacBook Pro 14"',
      price: 149900,
      originalPrice: 199900,
      image: 'https://images.pexels.com/photos/18105/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Aspecto excelente',
      rating: 4.9,
      reviews: 342,
      discount: 25,
    },
    {
      id: 'oferta-12',
      name: 'AirPods Pro',
      price: 19900,
      originalPrice: 27900,
      image: 'https://images.pexels.com/photos/3587620/pexels-photo-3587620.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Como nuevo',
      rating: 4.7,
      reviews: 567,
      discount: 29,
    },
  ],
  'guia-regalos': [
    {
      id: 'regalo-1',
      name: 'AirPods Pro',
      price: 19900,
      originalPrice: 27900,
      image: 'https://images.pexels.com/photos/3587620/pexels-photo-3587620.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Más Vendido',
      condition: 'Como nuevo',
      rating: 4.7,
      reviews: 567,
      discount: 29,
    },
    {
      id: 'regalo-2',
      name: 'Apple Watch Series 7',
      price: 29900,
      originalPrice: 41900,
      image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Buen estado',
      rating: 4.6,
      reviews: 456,
      discount: 29,
    },
  ],
  moviles: [
    {
      id: 'movil-1',
      name: 'iPhone 13 Pro',
      price: 69900,
      originalPrice: 99900,
      image: 'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Más Vendido',
      condition: 'Aspecto excelente',
      rating: 4.8,
      reviews: 245,
      discount: 30,
    },
    {
      id: 'movil-2',
      name: 'Samsung Galaxy S21',
      price: 59900,
      originalPrice: 89900,
      image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Buen estado',
      rating: 4.5,
      reviews: 189,
      discount: 33,
    },
    {
      id: 'movil-3',
      name: 'Google Pixel 6',
      price: 49900,
      originalPrice: 79900,
      image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Muy bueno',
      rating: 4.4,
      reviews: 145,
      discount: 38,
    },
  ],
  portatiles: [
    {
      id: 'laptop-1',
      name: 'MacBook Pro 14"',
      price: 149900,
      originalPrice: 199900,
      image: 'https://images.pexels.com/photos/18105/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Más Vendido',
      condition: 'Aspecto excelente',
      rating: 4.9,
      reviews: 342,
      discount: 25,
    },
    {
      id: 'laptop-2',
      name: 'Dell XPS 13',
      price: 89900,
      originalPrice: 129900,
      image: 'https://images.pexels.com/photos/18105/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Buen estado',
      rating: 4.7,
      reviews: 234,
      discount: 31,
    },
  ],
  tablets: [
    {
      id: 'tablet-1',
      name: 'iPad Air',
      price: 39900,
      originalPrice: 59900,
      image: 'https://images.pexels.com/photos/546822/pexels-photo-546822.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Buen estado',
      rating: 4.6,
      reviews: 128,
      discount: 33,
    },
    {
      id: 'tablet-2',
      name: 'iPad Pro 12.9"',
      price: 74900,
      originalPrice: 109900,
      image: 'https://images.pexels.com/photos/546822/pexels-photo-546822.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Más Vendido',
      condition: 'Aspecto excelente',
      rating: 4.8,
      reviews: 312,
      discount: 32,
    },
  ],
  consolas: [
    {
      id: 'consola-1',
      name: 'PlayStation 5',
      price: 49900,
      originalPrice: 69900,
      image: 'https://images.pexels.com/photos/1334601/pexels-photo-1334601.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Más Vendido',
      condition: 'Como nuevo',
      rating: 4.9,
      reviews: 567,
      discount: 29,
    },
    {
      id: 'consola-2',
      name: 'Xbox Series X',
      price: 49900,
      originalPrice: 69900,
      image: 'https://images.pexels.com/photos/1334601/pexels-photo-1334601.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Buen estado',
      rating: 4.7,
      reviews: 456,
      discount: 29,
    },
  ],
  smartwatches: [
    {
      id: 'watch-1',
      name: 'Apple Watch Series 7',
      price: 29900,
      originalPrice: 41900,
      image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Buen estado',
      rating: 4.6,
      reviews: 456,
      discount: 29,
    },
    {
      id: 'watch-2',
      name: 'Samsung Galaxy Watch 4',
      price: 24900,
      originalPrice: 34900,
      image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Más Vendido',
      condition: 'Aspecto excelente',
      rating: 4.5,
      reviews: 234,
      discount: 29,
    },
  ],
  audio: [
    {
      id: 'audio-1',
      name: 'AirPods Pro',
      price: 19900,
      originalPrice: 27900,
      image: 'https://images.pexels.com/photos/3587620/pexels-photo-3587620.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Más Vendido',
      condition: 'Como nuevo',
      rating: 4.7,
      reviews: 567,
      discount: 29,
    },
    {
      id: 'audio-2',
      name: 'Sony WH-1000XM5',
      price: 34900,
      originalPrice: 47900,
      image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Aspecto excelente',
      rating: 4.8,
      reviews: 298,
      discount: 27,
    },
  ],
  electrodomesticos: [
    {
      id: 'electro-1',
      name: 'Refrigerador Samsung',
      price: 89900,
      originalPrice: 129900,
      image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Buen estado',
      rating: 4.6,
      reviews: 178,
      discount: 31,
    },
    {
      id: 'electro-2',
      name: 'Lavadora LG',
      price: 74900,
      originalPrice: 109900,
      image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Más Vendido',
      condition: 'Aspecto excelente',
      rating: 4.7,
      reviews: 234,
      discount: 32,
    },
  ],
  mas: [
    {
      id: 'mas-1',
      name: 'Cámara Canon EOS',
      price: 64900,
      originalPrice: 99900,
      image: 'https://images.pexels.com/photos/606941/pexels-photo-606941.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: 'Más Vendido',
      condition: 'Muy bueno',
      rating: 4.8,
      reviews: 103,
      discount: 35,
    },
    {
      id: 'mas-2',
      name: 'Dron DJI Air 2S',
      price: 79900,
      originalPrice: 119900,
      image: 'https://images.pexels.com/photos/1526170/pexels-photo-1526170.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop',
      badge: null,
      condition: 'Aspecto excelente',
      rating: 4.8,
      reviews: 145,
      discount: 33,
    },
  ],
};
