
-- 1. Habilitar RLS en todas las tablas
ALTER TABLE public.admin_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campana_email_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campanas_email ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carrito_cupones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.codigos_descuento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_usages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cupon_uso ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cupones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cupones_descuento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalles_pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devoluciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.direcciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.envios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estadisticas_visualizacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estados_producto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos_envio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos_promocionales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gustos_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.imagenes_producto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventario_movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items_orden ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lista_deseos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs_transacciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marcas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metodos_pago ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ordenes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promociones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resenas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seguimiento_pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.variantes_producto ENABLE ROW LEVEL SECURITY;

-- 2. Eliminar políticas existentes para evitar conflictos
DROP POLICY IF EXISTS "Public Full Access" ON public.admin_credentials;
DROP POLICY IF EXISTS "Public Full Access" ON public.admin_preferences;
DROP POLICY IF EXISTS "Public Full Access" ON public.campana_email_logs;
DROP POLICY IF EXISTS "Public Full Access" ON public.campanas_email;
DROP POLICY IF EXISTS "Public Full Access" ON public.carrito_cupones;
DROP POLICY IF EXISTS "Public Full Access" ON public.cart_items;
DROP POLICY IF EXISTS "Public Full Access" ON public.cart_reservations;
DROP POLICY IF EXISTS "Public Full Access" ON public.categorias;
DROP POLICY IF EXISTS "Public Full Access" ON public.codigos_descuento;
DROP POLICY IF EXISTS "Public Full Access" ON public.company_settings;
DROP POLICY IF EXISTS "Public Full Access" ON public.coupon_audit_log;
DROP POLICY IF EXISTS "Public Full Access" ON public.coupon_usages;
DROP POLICY IF EXISTS "Public Full Access" ON public.coupons;
DROP POLICY IF EXISTS "Public Full Access" ON public.cupon_uso;
DROP POLICY IF EXISTS "Public Full Access" ON public.cupones;
DROP POLICY IF EXISTS "Public Full Access" ON public.cupones_descuento;
DROP POLICY IF EXISTS "Public Full Access" ON public.detalles_pedido;
DROP POLICY IF EXISTS "Public Full Access" ON public.devoluciones;
DROP POLICY IF EXISTS "Public Full Access" ON public.direcciones;
DROP POLICY IF EXISTS "Public Full Access" ON public.envios;
DROP POLICY IF EXISTS "Public Full Access" ON public.estadisticas_visualizacion;
DROP POLICY IF EXISTS "Public Full Access" ON public.estados_producto;
DROP POLICY IF EXISTS "Public Full Access" ON public.eventos_envio;
DROP POLICY IF EXISTS "Public Full Access" ON public.eventos_promocionales;
DROP POLICY IF EXISTS "Public Full Access" ON public.gustos_usuario;
DROP POLICY IF EXISTS "Public Full Access" ON public.imagenes_producto;
DROP POLICY IF EXISTS "Public Full Access" ON public.inventario_movimientos;
DROP POLICY IF EXISTS "Public Full Access" ON public.items_orden;
DROP POLICY IF EXISTS "Public Full Access" ON public.lista_deseos;
DROP POLICY IF EXISTS "Public Full Access" ON public.logs_transacciones;
DROP POLICY IF EXISTS "Public Full Access" ON public.marcas;
DROP POLICY IF EXISTS "Public Full Access" ON public.metodos_pago;
DROP POLICY IF EXISTS "Public Full Access" ON public.newsletter_subscriptions;
DROP POLICY IF EXISTS "Public Full Access" ON public.notificaciones;
DROP POLICY IF EXISTS "Public Full Access" ON public.ordenes;
DROP POLICY IF EXISTS "Public Full Access" ON public.pedidos;
DROP POLICY IF EXISTS "Public Full Access" ON public.productos;
DROP POLICY IF EXISTS "Public Full Access" ON public.promociones;
DROP POLICY IF EXISTS "Public Full Access" ON public.resenas;
DROP POLICY IF EXISTS "Public Full Access" ON public.seguimiento_pedido;
DROP POLICY IF EXISTS "Public Full Access" ON public.usuarios;
DROP POLICY IF EXISTS "Public Full Access" ON public.variantes_producto;

-- 3. Crear políticas permisivas (Permitir TODO a PUBLIC)
CREATE POLICY "Public Full Access" ON public.admin_credentials FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.admin_preferences FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.campana_email_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.campanas_email FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.carrito_cupones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.cart_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.cart_reservations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.categorias FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.codigos_descuento FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.company_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.coupon_audit_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.coupon_usages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.coupons FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.cupon_uso FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.cupones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.cupones_descuento FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.detalles_pedido FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.devoluciones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.direcciones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.envios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.estadisticas_visualizacion FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.estados_producto FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.eventos_envio FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.eventos_promocionales FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.gustos_usuario FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.imagenes_producto FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.inventario_movimientos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.items_orden FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.lista_deseos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.logs_transacciones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.marcas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.metodos_pago FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.newsletter_subscriptions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.notificaciones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.ordenes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.pedidos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.productos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.promociones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.resenas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.seguimiento_pedido FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.usuarios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access" ON public.variantes_producto FOR ALL USING (true) WITH CHECK (true);
